#!/usr/bin/env bash

##
## container environment variables
##

# assure folder does exist
mkdir -p /etc/container_environment

# dump environment into files and bash script
env                                            | \
awk -F "=" '{ print $1; }'                     | \
# filter these?
#grep -ve "HOME\|USER\|GROUP\|UID\|GID\|SHELL" | \
while read line; do
  # folder
  echo ${!line} > /etc/container_environment/$line;
  # export file
  echo "export $line=${!line}" >> /etc/container_environment.sh
done

##
## startup
##

exec /init-s6
