#!/usr/bin/env bash

# for loop should no loop if files weren't found
shopt -s nullglob

##
## dump environment into files and a bash script
##

# base for file and path
base=/etc/container_environment

# assure folder does exist
mkdir -p $base

echo "[pub-cont-envs] publishing container environments in $base..." | ts
env                                            | \
awk -F "=" '{ print $1; }'                     | \
# filter these?
#grep -ve "HOME\|USER\|GROUP\|UID\|GID\|SHELL" | \
while read line; do
  # folder
  echo ${!line} > $base/$line;
  # export file
  echo "export $line=${!line}" >> $base.sh
done
echo "[pub-cont-envs] done." | ts

##
## fix attributes (ownership and permissions)
##

echo "[fix-attrs] fixing file attributes (ownership & permission)..." | ts
for file in /etc/fix-attrs.d/*; do
  /usr/bin/fix-attrs fix $file
done
echo "[fix-attrs] done." | ts

# I don't know why it seems like 'fix-attrs' is not freeing file handles
# and therefore files which were accesed/modified cannot be used for
# execution. We flush all the dirty system buffers, and blocks until 
# they're clean.
s6-sync

##
## cont-init.d
##

echo "[cont-init.d] executing cont-init.d..." | ts
for file in /etc/cont-init.d/*; do
  /usr/bin/with-contenv $file
done
echo "[cont-init.d] done." | ts

##
## startup
##

echo "[s6-svscan] starting..." | ts
exec with-contenv s6-svscan -t0 /etc/s6
